# -*- coding: utf-8 -*-
"""Análise de Dados do Kaggle

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Sl9cmAJGjV54qB6lum5laqsFIutLw94
"""

from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette('viridis')

df = pd.read_csv("vgsales.csv")
df.info()
df.head(30)
colunas_relevantes = ["Rank", "Name", "Platform", "Year", "Genre", "Publisher", "NA_Sales", "Global_Sales"]
df_relevantes = df[colunas_relevantes]
df_relevantes.head(30)

df_fabricante = pd.read_csv("platforms_manufacturer.csv")
df_fabricante.info()
df_fabricante.head(30)

df_juntos = pd.merge(df_relevantes, df_fabricante, left_on="Platform", right_on="Platform")
df_juntos.info()
df_juntos.head(30)

df_juntos["Global_without_NA"] = df_juntos["Global_Sales"] - df_juntos["NA_Sales"]
df_juntos.head(30)

df_genero = (
    df_juntos.groupby("Genre")["Global_Sales"]
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)
print(df_genero.head(30))
# média de vendas globais de jogos por gêneros

plt.figure(figsize=(10,6))
plt.bar(df_genero["Genre"], df_genero["Global_Sales"])
plt.title("Média de Vendas Globais por Gênero")
plt.xlabel("Gênero")
plt.ylabel("Vendas Globais Médias (em milhões)")
plt.xticks(rotation=45)
plt.show()

# O gráfico mostra que gêneros como Platform e Shooter apresentam,
# em média, as maiores vendas globais por jogo. Já gêneros como Adventure e Strategy
# possuem valores médios bem menores, indicando que atraem nichos mais específicos.

plt.figure(figsize=(10,6))
plt.scatter(df_juntos["Global_Sales"], df_juntos["Global_without_NA"])
plt.title("Relação entre Vendas na América do Norte e no Resto do Mundo")
plt.xlabel("Vendas NA (em milhões)")
plt.ylabel("Global sem NA (em milhões)")
plt.show()

# O gráfico de dispersão mostra que há uma tendência positiva: quando um jogo
# vende mais na América do Norte, geralmente também apresenta boas vendas no
# resto do mundo. Porém, há pontos isolados que fogem da tendência, indicando
# jogos que tiveram sucesso mais localizado.